### ISSUE TITLE
Project Names can be used instead of IDs on certain resources

### ISSUE THREAD

**Issue by yannispgs** [vercel/terraform-provider-vercel#141]
For some resources, a Vercel Project Name can be used in replacement of an ID. However, in the Provider's documentation, it is not indicated whereas it is in the Vercel API Doc (e.g. `/v10/projects/{idOrName}/domains`).

I just tried with the "Shared Environment Variable" and managed to create one with 2 linked Projects. Being able to use the name is pretty useful as we don't have to retrieve the ID with a Data Source. I am using Terraform Cloud and one Data Source is billed as a Resource, so this kind of difference matters a lot.

I will check what resources arguments can be replaced by Projects Names and later update the Provider documentation.

**Comment by dglsparsons** [comment]
Hi @yannispgs. This was actually an intentional decision at the time of first writing this provider - as it keeps things simple. Project names can be updated or changed over time, causing a bit more maintenance, and except for your case of being billed for using a Data Source, I think it's the nicer pattern to follow. Also, not all APIs follow the idOrName pattern, so it might introduce a lot of inconsistency. 

I'm happy to accept changes you prepare though to make your life easier.

**Comment by yannispgs** [comment]
It's true this is a better way of using Terraform. We never change our resources name so we take the risk of using names instead of IDs.

It this was a choice when you were developing the provider I will let this as it is. People trying to do the same thing as me will probably be able to find that PR with Google indexing 😁
