### ISSUE TITLE
Seeming caching issue when deploying with files

### ISSUE THREAD

**Issue by rizowski** [vercel/terraform-provider-vercel#46]
I'm not sure if there is this ability so it's more of a question, but I'm currently running into an issue where the build is seemingly cached. Since I use typescript it has old type definitions and is failing saying the type doesn't exist. With the git ref deployment I can at least trigger a new build and bust the file cache when that happens. But with the file upload it doesn't seem like that same ability exists. Is it possible a build without cache can be exposed specifically for a file upload deployment?

**Comment by dglsparsons** [comment]
Hi, 

I'm not sure this would make sense to include as a concept to terraform, as it's pretty rare needing to bust the build cache and would have to exist as a persistent setting, rather than a toggle for a specific deployment. 

Is it possible to deploy via the [Vercel CLI](https://vercel.com/cli) and use the `--force` flag though? That should perform the same operation, but `--force` will ensure no cache is used.

**Comment by rizowski** [comment]
I think you're right about the toggle.

I could use the cli, but it does make the deployment quite a bit more complex since Vercel doesn't currently support custom lane deployments. So I have multiple projects per domain to account for that. At least with terraform it makes it easier to switch that configuration based on the lane I'm deploying to.

So for at least right now, I think I'll just use the source control deployment since I know that can at least rerun without cache through the UI.
