### ISSUE TITLE
Support managing environment variables separately

### ISSUE THREAD

**Issue by Inlustra** [vercel/terraform-provider-vercel#47]
Hi, 

I wondered if we'd eventually get a resource that allows us to manage environment variables entirely separately from the vercel_project resource.

I have multiple environments/terraform directories that look something like this: 
```
terraform/
├─ environments/
│  ├─ root/
│  │  ├─ main.tf
│  │  ├─ (Houses root vercel project)
│  │  ├─ (Houses overall DNS zones)
│  │  ├─ (Creates separate aws accounts listed below)
│  ├─ production/
│  │  ├─ main.tf
│  │  ├─ (Contains env specific resources such as DBs, APIs, etc...)
│  ├─ staging/
│  │  ├─ main.tf
│  │  ├─ (Contains env specific resources such as DBs, APIs, etc...)
```

Now those environment specific resources keys, urls and secrets are not accessible to the root account and I'd like to be able to manage those env vars in the individual terraform environments.

I've noticed that the chonark vercel package terraform does have this, but it's not maintained anymore.

**Comment by dglsparsons** [comment]
Hey, thanks for raising this. I like the idea and I'm not opposed to adding this functionality at all - especially when you've really nicely highlighted your use case, and it would enable some nice flexibility of use. 

I can see two potential issues though: 
1. It'd be hard to detect configuration drift (i.e. adding env variables in the Vercel UI rather than terraform wouldn't get picked up at all). 
2. It would potentially clash with the current behaviour of configuring environment variables on the `vercel_project` resource - i.e. one resource creates env_variables, another reads and removes them. 

I think 1. might be something just to accept (as you mentioned, it's how the Chronark provider works). 
I think 2. might require some flag on a `vercel_project` to allow environment variables to be managed separately - just to disable the behaviour of reading any environment variables as part of the `vercel_project` resource. Saying this, maybe it makes sense to allow _some_ env vars to be set, and others managed separately? I'm unsure of what the ideal behaviour for this would/should be.

**Comment by Inlustra** [comment]
I can totally see the benefit of allowing some env vars to be set in the vercel_project resource and some separately but that might add some additional complexity.

I know the the aws terraform docs do have a similar constraint with certain resources and have documented it like so: 
![image](https://user-images.githubusercontent.com/2565465/175513858-52f85ee3-a630-4b43-8ba1-7a4ad891fe18.png)
So maybe it's not an unheard of constraint if you were to allow either/or but not both.

The one written by chronark allows setting a single env var per-resource, with that approach, i suppose it's feasible to have "unmanaged" environment variables but I don't necessarily see that as a bad thing

**Comment by dglsparsons** [comment]
I think there could be a valid use-case where defining within the project makes sense, and also a valid use case where defining outside the project makes sense. Maybe it would make the most sense to support both. 

Also CC @BarnabyShearer - I know you're using env variables through Terraform, and I believe you've used both the `chronark` provider and this one? Do you have any thoughts on managing environment variables? :)

**Comment by dglsparsons** [comment]
Thanks for the super detailed writeup @BarnabyShearer. I think `aws_security_group` is a really nice comparison point too. 

I really like the third option you've raised, as it looks fairly simple from a consumer point of view, and captures drift really nicely. I'll try to get some time to implement this (hopefully soon). 

One thing I haven't factored in at all yet, is that integrations (vercel.com/integrations) also have the ability to set environment variables. I think the correct behaviour there would be to ignore any integration-set environment variables completely as far as terraform is concerned (so don't detect them for drift or show changes in them). 

Does that sound fair to you?

**Comment by Inlustra** [comment]
While the third option is certainly less verbose, it's also definitely less flexible.
If I were to pick I would still rather be able to manage individual environment variables, that way I don't have any mental overhead over which variables are managed where. 

The project target option I also find a little less intuitive, I would have to fit this concept into my project structure as opposed to being able to manage the DB environment variable alongside the DB resource itself. 

Just curious on peoples thoughts though - is there a downside to being verbose? It would certainly give us a much better apply and preview diff.

**Comment by ijin** [comment]
My use case is exactly like @Inlustra's where I need to set env vars per-terraform environments.

I think integration environment variables can be ignored, but maybe leave a _note_ in the terraform docs.

**Comment by dglsparsons** [comment]
It seems like individual environment variables would be preferable for everyone then. 

Would something akin to this fit everyone's use cases?
 
```terraform
resource "vercel_project_environment_variable" "foo" {
   project_id = "prj_...." 
   team_id    = "team_..."
   name       = "foo" 
   value      = "some-value"
   target     = [
       "production", 
       "preview"
   ]
}
```

**Comment by ijin** [comment]
That would work for me 😃 

I think I'll code it like this for multiple env vars.

```terraform
locals {
  NEXT_PUBLIC_ENDPOINT_URL = "https://${var.api_endpoint}
  SECRET                   = data.aws_ssm_parameter.secret.value
}

resource "vercel_project_environment_variable" "foo" {
  for_each  = toset(local.env_vars)

  project_id = "prj_...." 
  team_id    = "team_..."
  name       = each.key
  value      = each.value
   target    = [
       "production", 
       "preview"
   ]
}
```

One thing I need is the ability to add env vars for a specific **branch** , the CLI equivalent for

`vercel env add [name] [environment] [gitbranch]`

So `vercel env add some_key preview staging ` would add env vars for the **staging** branch.

I'm not sure how the syntax should be in terraform. Perhaps,

```terraform
   target    = [
       "preview[staging]"
   ]
```

but whatever works is fine.

**Comment by thraxil** [comment]
Just to add to this, one of the reasons I'd like to see environment variables treated as separate resources from the project is to improve the handling of secrets. We have dozens of environment variables, most of which aren't sensitive. But because there are a couple that are, it just marks the entire thing as sensitive and won't show any diff. Ie, any change at all results in a plan like:

```
Terraform will perform the following actions:

  # vercel_project.myproject will be updated in-place
  ~ resource "vercel_project" "myproject" {
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ environment                = (sensitive value)
        id                         = "prj_..."
        name                       = "myproject"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

In Terraform's view `environment` is a single attribute value, so the whole thing is either sensitive or not. Maybe I'm doing something very wrong, but it seems like with the current structure, you can either handle sensitive fields securely or you can have a usable plan, but you can't do both.

**Comment by dglsparsons** [comment]
Hey @Inlustra and all! 

We've added a `vercel_project_environment_variable` resource to the terraform provider in [v0.8.0](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.8.0). The documentation for it can be found [here](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/project_environment_variable). This allows managing environment variables separate from the `vercel_project` resource, with the small caveat that the two approaches can't both be used.  

Please give it a go and let me know if there are any issues!

**Comment by ijin** [comment]
Works as expected! Thanks, @dglsparsons ❗
